inherit_from: "/home/yejun688/Downloads/PycharmProject_04/MonoGS/configs/mono/endomapper/base_config.yaml"

Dataset:
  dataset_path: "/home/yejun688/Downloads/PycharmProject_04/MonoGS/datasets/Endo/sequence0"
  Calibration:
    fx: 472.64955100886374
    fy: 472.64955100886374
    cx: 479.5
    cy: 359.5
    k1: 0
    k2: 0
    p1: 0
    p2: 0
    k3: 0
    width: 960
    height: 720
    depth_scale: 1
    png_depth_scale: 0.1   # for depth image in png format        #exr文件是dm单位的 需要转换为cm单位
    crop_edge: 0
    distorted: False